//:: bg_const_inc.nss
//::

//:: Background Categories
const int BACKGROUND_TYPE_INVALID 		= 0;
const int BACKGROUND_TYPE_ETHNICITY 	= 1;
const int BACKGROUND_TYPE_SOCIAL_CLASS	= 2;
const int BACKGROUND_TYPE_BACKGROUND	= 3;
const int BACKGROUND_TYPE_DEITY			= 4;
const int BACKGROUND_TYPE_PROFICIENCY	= 5;
const int BACKGROUND_TYPE_AGE			= 6;
const int BACKGROUND_TYPE_DISABILITY	= 7;

//:: Social Standings
const int SOCIAL_CLASS_LOWER 			= 1150;
const int SOCIAL_CLASS_MIDDLE 			= 1151;
const int SOCIAL_CLASS_UPPER 			= 1152;

//:: Ethnicities and Subraces
const int ETHNICITY_SHADOW 			= 1176;
const int ETHNICITY_COPPER_ELF		= 1177;
const int ETHNICITY_GREEN_ELF		= 1178;
const int ETHNICITY_DARK_ELF		= 1179;
const int ETHNICITY_SILVER_ELF		= 1180;
const int ETHNICITY_GOLD_ELF		= 1181;
const int ETHNICITY_GOLD_DWARF		= 1182;
const int ETHNICITY_GREY_DWARF		= 1183;
const int ETHNICITY_SHIELD_DWARF	= 1184;
const int ETHNICITY_OUTSIDER		= 1185;
const int ETHNICITY_AASIMAR			= 1186;
const int ETHNICITY_TIEFLING		= 1187;
const int ETHNICITY_CALISHITE		= 1381;
const int ETHNICITY_CHONDATHAN		= 1382;
const int ETHNICITY_DAMARAN			= 1383;
const int ETHNICITY_ILLUSKAN		= 1384;
const int ETHNICITY_MULAN			= 1385;
const int ETHNICITY_RASHEMI			= 1386;
const int ETHNICITY_TETHYRIAN		= 1387;
const int ETHNICITY_OTHER			= 1388;



const int BACKGROUND_AFFLUENCE = 1153;
const int BACKGROUND_BRAWLER = 1154;
const int BACKGROUND_COSMOPOLITAN = 1155;
const int BACKGROUND_CRUSADER = 1156;
const int BACKGROUND_DUELIST = 1157;
const int BACKGROUND_EVANGELIST = 1158;
const int BACKGROUND_FORESTER = 1159;
const int BACKGROUND_HARD_LABORER = 1160;
const int BACKGROUND_HEALER = 1161;
const int BACKGROUND_KNIGHT = 1162;
const int BACKGROUND_HEDGEMAGE = 1163;
const int BACKGROUND_MENDICANT = 1164;
const int BACKGROUND_MERCHANT = 1165;
const int BACKGROUND_METALSMITH = 1166;
const int BACKGROUND_MINSTREL = 1167;
const int BACKGROUND_OCCULTIST = 1168;
const int BACKGROUND_SABOTEUR = 1169;
const int BACKGROUND_SCOUT = 1170;
const int BACKGROUND_SNEAK = 1171;
const int BACKGROUND_SOLDIER = 1172;
const int BACKGROUND_TRAVELER = 1173;
const int BACKGROUND_SPELLFIRE = 1174;
const int BACKGROUND_NAT_LYCAN = 1175;
const int BACKGROUND_AMN_TRAINED = 1389;
const int BACKGROUND_CALISHITE_TRAINED = 1390;
const int BACKGROUND_CHURCH_ACOLYTE = 1392;
const int BACKGROUND_CARAVANNER = 1391;
const int BACKGROUND_CIRCLE_BORN = 1393;
const int BACKGROUND_ENLIGHTENED_STUDENT = 1394;
const int BACKGROUND_HAREM_TRAINED = 1395;
const int BACKGROUND_HARPER = 1396;
const int BACKGROUND_KNIGHT_SQUIRE = 1397;
const int BACKGROUND_TALFIRIAN = 1398;
const int BACKGROUND_THEOCRAT = 1399;
const int BACKGROUND_WARD_TRIAD = 1400;
const int BACKGROUND_ZHENTARIM = 1401;

const int FEAT_LANGUAGE_ABYSSAL = 1650;
const int FEAT_LANGUAGE_ALZHEDO = 1651;
const int FEAT_LANGUAGE_ANIMAL = 1652;
const int FEAT_LANGUAGE_AQUAN = 1653;
const int FEAT_LANGUAGE_ASSASSINS_CANT = 1654;
const int FEAT_LANGUAGE_AURAN = 1655;
const int FEAT_LANGUAGE_CELESTIAL = 1656;
const int FEAT_LANGUAGE_CHESSENTAN = 1657;
const int FEAT_LANGUAGE_CHONDATHAN = 1658;
const int FEAT_LANGUAGE_CHULTAN = 1659;
const int FEAT_LANGUAGE_DAMARAN = 1660;
const int FEAT_LANGUAGE_DRACONIC = 1661;
const int FEAT_LANGUAGE_DROW = 1662;
const int FEAT_LANGUAGE_DROW_HAND_CANT = 1663;
const int FEAT_LANGUAGE_DRUIDIC = 1664;
const int FEAT_LANGUAGE_DUERGAR = 1665;
const int FEAT_LANGUAGE_DWARVEN = 1666;
const int FEAT_LANGUAGE_ELVEN = 1667;
const int FEAT_LANGUAGE_GIANT = 1668;
const int FEAT_LANGUAGE_GNOMISH = 1669;
const int FEAT_LANGUAGE_GOBLIN = 1670;
const int FEAT_LANGUAGE_HALFLING = 1671;
const int FEAT_LANGUAGE_IGNAN = 1672;
const int FEAT_LANGUAGE_ILLUSKAN = 1673;
const int FEAT_LANGUAGE_IMASKARI = 1674;
const int FEAT_LANGUAGE_INFERNAL = 1675;
const int FEAT_LANGUAGE_LANTANESE = 1677;
const int FEAT_LANGUAGE_MAZTILAN = 1678;
const int FEAT_LANGUAGE_MULANESE = 1679;
const int FEAT_LANGUAGE_MULHORANDI = 1680;
const int FEAT_LANGUAGE_ORCISH = 1681;
const int FEAT_LANGUAGE_RASHEMI = 1682;
const int FEAT_LANGUAGE_SHAARAN = 1683;
const int FEAT_LANGUAGE_SYLVAN = 1684;
const int FEAT_LANGUAGE_TALFIRIC = 1685;
const int FEAT_LANGUAGE_TERRAN = 1686;
const int FEAT_LANGUAGE_THIEVES_CANT = 1687;
const int FEAT_LANGUAGE_TROGLODYTE = 1688;
const int FEAT_LANGUAGE_UNDERCOMMON = 1689;

